# Generated by Django 2.0.1 on 2018-02-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
